### ISSUE TITLE
Is it possible to run jcast with splicing events that are not from rMATS ? 

### ISSUE THREAD

**Issue by gouthamatla** [ed-lau/jcast#1]
Hi,

I am very interested to run jcast on few of my alternatively spliced transcripts, especially step 2 of the publication. I already have differentially used junctions, not from rMATS but from leafcutter,  and I am curious to know the resulting protein sequences with usage of alternate junctions.  Could you let me know if I could adapt it for this purpose ? Or is it possible to generate the spliced events from GTF using rMATs but without using BAM files ?  

Thanks in advance,
Goutham A

**Comment by ed-lau** [comment]
Hi Goutham,

jcast currently only takes in rMATS output rather than from leafcutter, although if there is enough interest we may go back and make it a more general purpose software in the future (accepting different workflows).

If you have the fastq or bam files it shouldn’t be too hard to re-run rMATS. As far as I know you will need more than GTF since rMATS has to count the junction specific reads. Hope that helps!

Best wishes,
Edward

**Comment by gouthamatla** [comment]
Hi Edward,

Thanks for the quick response. I am not looking for differential splicing but just quantifying junctions and trying to asses the consequence of using alternate junctions in a single tissue especially junctions that are associated with genetic variants, like sQTL junctions.

Does jcast relies just on splicing events from rMATs or also on quantifications ? If I don't have two conditions or tissues, how would you suggest to run rMATs that can be fed in to jcast ? 


Thanks,
Goutham A
