### ISSUE TITLE
MXE output header

### ISSUE THREAD

**Issue by pravsaz** [ed-lau/jcast#15]
FASTA Header of T1 both MXE AS shows same coordinates. Shouldn't it be coordinates of exon 1 in MXE1 and exon 2 in MXE2?

**see example below:**

**rMATS MXE table**
ID	GeneID	geneSymbol	chr	strand	1stExonStart_0base	1stExonEnd	2ndExonStart_0base	2ndExonEnd	upstreamES	upstreamEE	downstreamES	downstreamEE	ID
0	ENSG00000160305	DIP2A	chr21	+	46498581	46498833	46504360	46504489	46496987	46497107	46509256	46509376	0

**FASTA headers:**
>sp|Q14689|DIP2A_HUMAN|ENSG00000160305|MXE1|0|chr21|46496988:46497107|46498582:46498833|+2|r133|T1
>sp|Q14689|DIP2A_HUMAN|ENSG00000160305|MXE2|0|chr21|46496988:46497107|46498582:46498833|+2|r133|T1

**Comment by ed-lau** [comment]
That is as intended since the FASTA header currently only includes the coordinates of the upstream/downstream exons (rather than the alt exons). The thinking was to not have the header be too long, but we would be interested to hear from you if including all the exons will be useful for your applications.
