### ISSUE TITLE
Installing jcast and dependencies without 'sudo'.

### ISSUE THREAD

**Issue by mranjan1** [ed-lau/jcast#9]
This is not a jcast related issue per say. On my desktop, running jcast with 8 threads and p<0.001 has already taken more than 6 hours. I would like to run it on our HPCC but I don't have sudo rights on it. Is there a workaround this?

**Comment by ed-lau** [comment]
I will likely deploy the new version to PyPI soon so it can be installed via pip.

On a related note, most of the running time currently stems from making web API calls to Uniprot to determine which transcript is the canonical sequence. There is an option inside params.py to turn that off and assume the longest transcript as canonical, but that is not ideal since the longest sequence is not always canonical. I had in mind to implement reading the APPRIS tags if they are present in the gtf/gff files, but for now Uniprot is the best option. JCast does cache the retrieved sequences, so if you ever had to translate the same sequences again it should run faster.

**Comment by ed-lau** [comment]
There is a new version on PyPI (https://pypi.org/project/jcast/0.3.1/) that can be installed via pip. It also fixes an issue of retrieving canonical sequences from Uniprot if the transcript is versioned as in some Gencode gtf.

**Comment by mranjan1** [comment]
Thank you so much. I was trying to figure out why is my canonical file empty and I have only orphan files but then I saw your last reply and it's working like a charm now. I had some strange issue where I needed to uninstall jcast twice or thrice using pip3 uninstall jcast and it was only after, that the latest version of jcast could be run. I think I messed up the installation with Github installation and pip installation. Anyway, for now it seems to be working flawlessly. Thank you so much again.
